version: '3'

services:
  pluto:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1234:1234'
    volumes:
      - .:/work
    command: julia --project=. -e 'import Pluto; Pluto.run(host="0.0.0.0", require_secret_for_access=false)'